version: '3.3'

configs:
  bf_config:
    file: ./config.php

  haproxy_config:
    file: ./haproxy.cfg

networks:
  bf:

services:
  web:
    image: docker.cs.hioa.no/kyrrepublic/bf:latest

    configs:
      - source: bf_config
        target: /var/www/html/config.php
    ports:
      - "80"
    networks:
        - bf

    environment:
      BF_MEMCACHE_SERVER: memcache

    deploy:
      replicas: 3

  memcache:
    image: memcached

    networks:
      - bf

  db_balance:
    image: haproxy

    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg

    networks:
      - bf
