version: "3.3"

configs:
  bf_config:
    file: ./config.php.swarm

  haproxy_config:
    file: ./haproxy_cache.cfg

networks:
  bf:
    attachable: true

services:
  web:
    image: 192.168.128.23:5000/bf:v17
    
    restart: always

    configs:
      - source: bf_config
        target: /var/www/html/config.php

    networks:
        - bf
    volumes:
        - type: bind
          source: /bf_images
          target: /var/www/html/images

    environment:
      BF_MEMCACHE_SERVER: memcache
      BF_DB_HOST: balancer
      BF_DB_PORT: 26257
      BF_DB_USER: bfuser
      BF_DB_NAME: bf
      BF_FRONTPAGE_LIMIT: 500
      
    deploy:
      replicas: 3

  memcache:
    image: 192.168.128.23:5000/memcached
    
    networks:
      - bf

  balancer:
    image: 192.168.128.23:5000/haproxy
    
    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg

    networks:
      - bf
      
    deploy:
      replicas: 3

    ports:
      - "1936:1936"
      - "80:80"


