version: "3.3"

configs:
  bf_config:
    file: ./config.php.swarm

  haproxy_config:
    file: ./haproxy.cfg

networks:
  bf:
    attachable: true

services:
  varnish:
    image: varnish
    build: ./varnish
    restart: always
    ports:
      - "80:80"
    networks:
      - bf
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    environment:
      VARNISH_SIZE: 1G
      # VARNISH_HTTP_PORT: 8080
    deploy:
      replicas: 3

  web:
    image: bookface
    build: ./.

    configs:
      - source: bf_config
        target: /var/www/html/config.php
    # ports:
    #   - "1234:80"
    networks:
      - bf
    volumes:
      - type: bind
        source: /bf_images
        target: /var/www/html/images

    environment:
      BF_MEMCACHE_SERVER: memcache
      BF_DB_HOST: db_balance
      BF_DB_PORT: 26257
      BF_DB_USER: bfuser
      BF_DB_NAME: bf
      BF_FRONTPAGE_LIMIT: 8000

    deploy:
      replicas: 3

  memcache:
    image: memcached
    restart: always

    networks:
      - bf

  db_balance:
    image: haproxy

    restart: always

    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg

    networks:
      - bf

    ports:
      - "1936:1936"
